### ISSUE TITLE
What can i do? 

### ISSUE THREAD

**Issue by tomhohenstein** [CfA-Library/Training#1]
@dbouquin what can i do to help with Wednesday's training?

**Comment by dbouquin** [comment]
Your timing is perfect 😄 I'm just sending out the reminder to sign up emails and instructions to people who have already signed up to install git before the workshop today. I made a website using the Software Carpentry infrastructure here: https://dbouquin.github.io/2016-10-12-cfa-git/
If you can just review what I have here already, and be ready to support people with questions, that would be excellent!

**Comment by tomhohenstein** [comment]
sounds good 👍
